apiVersion: v1
kind: Service
metadata:
  name: generate-key-service
  namespace: dpki
spec:
  type: NodePort
  ports:
  - port: 9090
    targetPort: 9090
    nodePort: 30741
  selector:
    app: generate-key-deployment
